# Generated by Django 5.0.7 on 2024-08-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_alter_transactions_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='account_type',
            new_name='transaction_type',
        ),
    ]
