# Generated by Django 5.0.7 on 2024-07-22 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomemadeMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('portion_grams', models.FloatField()),
                ('ounces', models.FloatField()),
                ('calories', models.FloatField()),
                ('sugar_grams', models.FloatField()),
                ('sat_fat_grams', models.FloatField()),
                ('protein_grams', models.FloatField()),
                ('fiber_grams', models.FloatField()),
                ('purchase_location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('portion_grams', models.FloatField()),
                ('ounces', models.FloatField()),
                ('calories', models.FloatField()),
                ('sugar_grams', models.FloatField()),
                ('sat_fat_grams', models.FloatField()),
                ('protein_grams', models.FloatField()),
                ('fiber_grams', models.FloatField()),
                ('purchase_location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PremadeMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('portion_grams', models.FloatField()),
                ('ounces', models.FloatField()),
                ('calories', models.FloatField()),
                ('sugar_grams', models.FloatField()),
                ('sat_fat_grams', models.FloatField()),
                ('protein_grams', models.FloatField()),
                ('fiber_grams', models.FloatField()),
                ('purchase_location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('total_portion_grams', models.FloatField()),
                ('serving_grams', models.FloatField()),
                ('serving_ounces', models.FloatField()),
                ('serving_calories', models.FloatField()),
                ('serving_sugar_grams', models.FloatField()),
                ('serving_fat_grams', models.FloatField()),
                ('serving_protein_grams', models.FloatField()),
                ('serving_fiber_grams', models.FloatField()),
                ('purchase_location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='KcalIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_grams', models.FloatField()),
                ('homemade_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Health.homemademeal')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Health.ingredient')),
                ('premade_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Health.premademeal')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Health.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Health.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Health.recipe')),
            ],
        ),
    ]
