# Generated by Django 5.0.7 on 2024-07-31 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0002_net_kcal_workout_remove_kcalin_homemade_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='net_kcal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
